### ISSUE TITLE
README TODO

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/tbranyen.com#11]
- [x] Introduction.
- [ ] Technology used.
- [ ] Projects spawned from this.
- [ ] How to set up the CMS.
- [ ] Setting up the content repo.
- [ ] Creating a page.
- [ ] Creating a template. 
- [ ] LICENSE
