### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/tbranyen.com#6]
High (Will block open sourcing):
- [ ] Normalize a given resource path (in posts) by revision and location. 
- [ ] Improve link hover color/transition.
- [ ] Internationalization.
- [ ] Revamp static generator to not suck at hidden urls.

Medium (May block open sourcing):
- [x] Break the cluster/master worker code into it's own module.
- [ ] Fix Grunt watch task to not fail reloading the application during changes.
- [ ] Optimizations to images, HTML, JavaScript, etc.
- [ ] Convert from symlink to submodule.

Low (Won't block open sourcing):
- [ ] Suggest translation button.
- [x] Track remote changes (from something like GitHub).
- [x] Handle post-receive hooks from GitHub.
- [ ] Implement gap.js.

Done:
- [x] Themes.
- [x] Refactor styles to use modular setup.
- [x] Generate static content process for production.
- [x] Trivial configuration.
- [x] Add code coverage and coveralls badge.
- [x] Add unit tests and travis-ci badge.
- [x] Add dependencies badge.
- [x] Adjust the line height for inline code blocks so that there is better vertical separation.
- [x] Always read from the filesystem during development.
- [x] Fix overlapping with code background, CoffeeScript post as an example.  (Caused by clearfix removal).
- [x] Break out content loading into its own module. (maestro)
- [x] Convert nodegit to git-node.
- [x] Rewrite Combyne to not be a broken piece of shit.
